"""真实执行器（P2）：把生成的用例编译成真实 pytest，在 tcms-can-test 上执行。

与 executor.py（一期 mock 启发式检查）的关键区别：
    * 这里的 pass/fail 是**真实 pytest 运行结果**——生成的用例被编译为真实
      测试函数，调用 tcms-can-test 的 db/simulator（真实编码/仿真逻辑），
      由上游测试基建（conftest fixture）执行，任何断言失败都是真失败；
    * 不可编译的用例记 uncompiled（口径含入分母），诚实反映生成质量。

设计（"模板化编译器"而非"通用代码生成"）：
    用例的 steps/expected 是自然语言，无法让 LLM 任意自由代码进入执行。
    本项目映射到一组**确定性语义原语**（上游已实测的 API）：
      1. 编码边界拒绝/接受  —— 调用 db.encode_message 断言 raises/成功
      2. 注入 + 总线断言（超速/门/心跳）—— 调用 simulator + parser.collect
    匹配不上的用例：不进执行（uncompiled），不猜、不硬凑。

API：
    compile_case(case, scenario_ctx=None) -> str | None   # pytest 函数源码
    run_real(cases, upstream_root, workdir=None, markers=None) -> RealExecResult
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from tcms_ai_testgen.models import GeneratedCase

#: 编码边界语义关键字 -> (报文, 信号, 越界值, 接受上限值) —— 与 tcms.dbc 实测对齐
_ENCODE_BOUNDS: dict[tuple[str, str], tuple[str, str, str, str]] = {
    ("VehicleSpeed", "SpeedKmh"): ("VehicleSpeed", "SpeedKmh", "200.1", "200.0"),
    ("TractionBrakeHandle", "HandlePosition"): ("TractionBrakeHandle", "HandlePosition", "17", "16"),
    ("EnergyStatus", "SocPercent"): ("EnergyStatus", "SocPercent", "101", "100"),
    ("EnergyStatus", "BatteryTemp"): ("EnergyStatus", "BatteryTemp", "-41", "-40"),
}

#: 中文语义别名 -> 键（真实 LLM 用例不会写英文报文名，写"车速/手柄/SOC"）
_SEMANTIC_ALIASES: dict[str, tuple[str, str]] = {
    "车速": ("VehicleSpeed", "SpeedKmh"),
    "超速": ("VehicleSpeed", "SpeedKmh"),
    "速度": ("VehicleSpeed", "SpeedKmh"),
    "speed": ("VehicleSpeed", "SpeedKmh"),
    "手柄": ("TractionBrakeHandle", "HandlePosition"),
    "级位": ("TractionBrakeHandle", "HandlePosition"),
    "handle": ("TractionBrakeHandle", "HandlePosition"),
    "soc": ("EnergyStatus", "SocPercent"),
    "电量": ("EnergyStatus", "SocPercent"),
    "batterytemp": ("EnergyStatus", "BatteryTemp"),
    "电池温度": ("EnergyStatus", "BatteryTemp"),
    "温度": ("EnergyStatus", "BatteryTemp"),
}

_HEADER = """\
# AUTO-GENERATED by tcms_ai_testgen.executor_real (P2). Do not edit.
import pytest
from cantools.database.errors import EncodeError
from tcms import protocol as proto
from tcms.parser import collect


def _encode(db, name, **signals):
    for sig in db.get_message_by_name(name).signals:
        signals.setdefault(sig.name, 0)
    return db.encode_message(name, signals)
"""

#: 把文本中出现的物理量关键字映射到真实符号（供生成注释/追踪）
_TRACE_KEYWORDS = ("越界", "上限", "下限", "拒绝", "超速", "报警", "车门", "心跳")


def _trace_hint(case: GeneratedCase) -> str:
    hits = [w for w in _TRACE_KEYWORDS if w in (case.purpose + case.expected)]
    return f"  # ai-gen: {case.purpose}  [{', '.join(hits) if hits else 'no-trace'}]"


def _compile_encode_bound(case: GeneratedCase) -> Optional[str]:
    """编码边界拒绝/接受类用例（最稳的真实断言，不需总线/定时）。"""
    text = case.purpose + " " + case.expected + " " + case.name
    low = text.lower()
    # 先按中文语义别名匹配，再按报文/信号名匹配
    for alias, key in _SEMANTIC_ALIASES.items():
        if alias.lower() in low:
            (msg, sig, over_val, ok_val) = _ENCODE_BOUNDS[key]
            break
    else:
        for key, (msg, sig, over_val, ok_val) in _ENCODE_BOUNDS.items():
            msg_name, sig_name = key
            if msg_name in text or sig_name in text or msg_name.replace("_", "") in text.replace("_", ""):
                break
        else:
            return None
    # 拒绝语义：越界/拒绝/超过/超出/上限/不应/禁止（接受语义则反之）
    reject_hint = any(w in text for w in ("越界", "拒绝", "超过", "超出", "上限", "不应", "禁止", "不允许"))
    accept_hint = any(w in text for w in ("上限可编码", "可编码", "编码成功", "允许", "正常编码", "物理上限"))
    if reject_hint and not accept_hint:
        return (
            f"def {case.name}(db):{_trace_hint(case)}\n"
            f"    with pytest.raises(EncodeError):\n"
            f"        _encode(db, \"{msg}\", {sig}={over_val})\n"
        )
    return (
        f"def {case.name}(db):{_trace_hint(case)}\n"
        f"    data = _encode(db, \"{msg}\", {sig}={ok_val})\n"
        f"    assert len(data) == 8\n"
    )


def _compile_simulator(case: GeneratedCase) -> Optional[str]:
    """注入 + 总线断言类（超速/车门/心跳丢失）。依赖上游 conftest 的 simulator。"""
    text = case.purpose + " " + case.expected + " " + case.name
    if "超速" in text or "overspeed" in text.lower():
        return (
            f"def {case.name}(bus, db, simulator):{_trace_hint(case)}\n"
            f"    simulator.set_speed(165.0)\n"
            f"    simulator.send_alarm(1, 2, Overspeed=True)\n"
            f"    import time; time.sleep(0.1)\n"
            f"    collected = collect(bus, 0.3, {{proto.VEHICLE_SPEED, proto.ALARM_EVENT}}, db)\n"
            f"    speed = collected[proto.VEHICLE_SPEED][-1][\"SpeedKmh\"]\n"
            f"    alarm = collected[proto.ALARM_EVENT][-1]\n"
            f"    assert speed > 160.0\n"
            f"    assert alarm[\"Overspeed\"] == 1\n"
        )
    if "车门" in text or "door" in text.lower():
        return (
            f"def {case.name}(bus, db, simulator):{_trace_hint(case)}\n"
            f"    simulator.set_door_state(1, 2)\n"
            f"    import time; time.sleep(0.15)\n"
            f"    collected = collect(bus, 0.3, {{proto.DOOR_CONTROL}}, db)\n"
            f"    f = collected[proto.DOOR_CONTROL][-1]\n"
            f"    # 真实解码：Door 状态为 VAL_ 枚举字符串（'Closed'/'Open'/'Fault'/'Unknown'）\n"
            f"    assert f[\"Door2State\"] == \"Fault\"\n"
            f"    assert f[\"AllDoorsClosed\"] == 0\n"
        )
    if "心跳" in text or "heartbeat" in text.lower():
        return (
            f"def {case.name}(bus, db, simulator):{_trace_hint(case)}\n"
            f"    simulator.stop_message(proto.TCMS_HEARTBEAT)\n"
            f"    import time; time.sleep(0.25)\n"
            f"    while bus.recv(timeout=0.01) is not None:\n"
            f"        pass\n"
            f"    from tcms.parser import count_frames\n"
            f"    assert count_frames(bus, 0.8, proto.TCMS_HEARTBEAT) == 0\n"
        )
    return None


def compile_case(case: GeneratedCase) -> Optional[str]:
    """把一条生成用例编译为真实 pytest 函数源码；不可编译返回 None。"""
    if not case.name.startswith("test_"):
        return None
    return _compile_encode_bound(case) or _compile_simulator(case)


@dataclass
class RealExecResult:
    """真实执行结果（口径对齐 docs/metrics.md exec_pass_rate）。"""

    total: int = 0
    compiled: int = 0
    passed: int = 0
    failed: int = 0
    stdout: str = ""
    report_path: Optional[str] = None

    @property
    def exec_pass_rate(self) -> float:
        return self.passed / self.compiled if self.compiled else 0.0

    @property
    def compile_rate(self) -> float:
        return self.compiled / self.total if self.total else 0.0

    def as_dict(self) -> dict[str, float | int | str | None]:
        return {
            "total": self.total,
            "compiled": self.compiled,
            "passed": self.passed,
            "failed": self.failed,
            "compile_rate": round(self.compile_rate, 3),
            "exec_pass_rate": round(self.exec_pass_rate, 3),
            "report_path": self.report_path,
        }


def run_real(
    cases: list[GeneratedCase],
    upstream_root: str | Path,
    *,
    keep_artifacts: bool = False,
) -> RealExecResult:
    """把一批用例编译成单个 pytest 文件并在 tcms-can-test 仓库环境执行。

    约定：
    - 生成文件写入 ``<upstream>/tests/test_ai_generated_p2.py``（conftest 可见）；
      执行 ``<upstream .venv 或 PATH python> -m pytest <file> -q``，cwd=upstream_root
      让 conftest.py 与 tcms 包可导入；
    - keep_artifacts=True 时保留生成文件并回填 report_path（演示/审计用）。
    """
    root = Path(upstream_root)

    bodies: list[str] = []
    compiled_count = 0
    for case in cases:
        body = compile_case(case)
        if body is None:
            continue
        bodies.append(body)
        compiled_count += 1
    if not bodies:
        # 无一条可编译：不需要上游环境，直接返回（口径：compile_rate=0）
        return RealExecResult(total=len(cases), compiled=0, passed=0, failed=0)

    if not (root / "tests" / "conftest.py").is_file():
        raise FileNotFoundError(f"非 tcms-can-test 仓库根: {root}")
    tests_dir = root / "tests"

    code = _HEADER + "\n\n" + "\n\n".join(bodies) + "\n"

    # 写入上游 tests/（conftest 可见）——不落根目录避免污染
    gen_path = tests_dir / "test_ai_generated_p2.py"
    gen_path.write_text(code, encoding="utf-8")

    py = root / ".venv" / "Scripts" / "python.exe"
    if not py.is_file():  # 环境探测失败就退回 PATH python
        py = None
    cmd = [str(py) if py else "python", "-m", "pytest", str(gen_path), "-q", "--no-header"]
    proc = subprocess.run(
        cmd,
        cwd=root,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=120,
    )
    stdout = proc.stdout
    passed = 0
    failed = 0
    # pytest -q 摘要：`N passed, M failed`（含 skipped 词需剥离）
    summary_line = [ln for ln in stdout.splitlines() if " passed" in ln or " failed" in ln]
    if summary_line:
        for ln in summary_line:
            m = re.search(r"(\d+) passed", ln)
            if m:
                passed = int(m.group(1))
            m = re.search(r"(\d+) failed", ln)
            if m:
                failed = int(m.group(1))
    report_path = str(gen_path) if keep_artifacts else None
    if not keep_artifacts:
        try:
            gen_path.unlink()
        except OSError:
            pass

    return RealExecResult(
        total=len(cases),
        compiled=compiled_count,
        passed=passed,
        failed=failed,
        stdout=stdout,
        report_path=report_path,
    )
