"""真实执行器（P2+）：把 GeneratedCase.execution DSL 编译成真实 pytest 执行。

v2 设计（对齐 docs/PLAN.md 主线）：
    生成器（mock/真 LLM 同契约）输出机器可读 execution（白名单原语），
    本模块把它编译为调用上游 tcms-can-test 真实 API 的 pytest 函数，
    由上游 conftest fixture（db/bus/simulator）执行。不可编译/无 execution
    的用例计 uncompiled（口径诚实，compile_rate<1 反映生成质量）。

白名单原语 → 真实代码映射（与上游实测 API 一一对应）：
    setup:
      set_speed(kmh)                    -> simulator.set_speed
      set_handle(pos,dir)               -> simulator.set_handle
      set_door_state(index,state)       -> simulator.set_door_state
      stop_message(message)             -> simulator.stop_message(proto.xxx)
      send_alarm(code,level,**flags)    -> simulator.send_alarm
      inject_fault(fault)               -> 台账注入（faultlevel 语义）
      recover_fault(fault)              -> 恢复
    expect:
      expect_signal(msg,sig,equals)     -> collect 后解码断言（枚举文本/数值）
      expect_no_frames(msg)             -> count_frames == 0
      expect_encode_error(msg,sig,val)  -> db.encode_message 抛 EncodeError
      expect_encode_ok(msg,sig,val)     -> db.encode_message 成功且 len==8
      expect_action(fault,action)       -> faultlevel.action_for 判等
      expect_frames_at_least(msg,n)     -> count_frames >= n
"""

from __future__ import annotations

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from tcms_ai_testgen.models import GeneratedCase

#: 上游 protocol 报文名常量（供 stop_message / collect 引用）
_MESSAGE_CONST = {
    "TCMS_Heartbeat": "TCMS_HEARTBEAT",
    "VehicleSpeed": "VEHICLE_SPEED",
    "TractionBrakeHandle": "TRACTION_BRAKE_HANDLE",
    "DoorControl": "DOOR_CONTROL",
    "AlarmEvent": "ALARM_EVENT",
    "PantographStatus": "PANTOGRAPH_STATUS",
    "BrakeSystem": "BRAKE_SYSTEM",
    "EnergyStatus": "ENERGY_STATUS",
}

#: 枚举信号表（镜像 tcms.dbc VAL_：message.signal -> {raw: 解码文本}）。
#: expect_encode_ok 的往返断言需要它——枚举信号 encode 收 raw、decode 出文本，
#: 直接比数字会假失败（AlarmLevel=0 编码成功但 decode 得 'Info'）。
ENUM_SIGNAL_TEXTS: dict[tuple[str, str], dict[int, str]] = {
    ("TCMS_Heartbeat", "NodeStatus"): {0: "PowerOff", 1: "Standby", 2: "Active", 3: "Fault"},
    ("TCMS_Heartbeat", "RunMode"): {0: "Offline", 1: "Manual", 2: "ATO", 3: "Shunting", 4: "Emergency"},
    ("TractionBrakeHandle", "Direction"): {0: "Neutral", 1: "Forward", 2: "Reverse", 3: "Invalid"},
    ("DoorControl", "Door1State"): {0: "Closed", 1: "Open", 2: "Fault", 3: "Unknown"},
    ("DoorControl", "Door2State"): {0: "Closed", 1: "Open", 2: "Fault", 3: "Unknown"},
    ("DoorControl", "Door3State"): {0: "Closed", 1: "Open", 2: "Fault", 3: "Unknown"},
    ("DoorControl", "Door4State"): {0: "Closed", 1: "Open", 2: "Fault", 3: "Unknown"},
    ("AlarmEvent", "AlarmLevel"): {0: "Info", 1: "Warning", 2: "Severe", 3: "Emergency"},
    ("EnergyStatus", "ChargeState"): {0: "Idle", 1: "Charging", 2: "Discharging", 3: "Fault"},
}

_HEADER = """\
# AUTO-GENERATED by tcms_ai_testgen.executor_real (execution DSL). Do not edit.
import time

import pytest
from cantools.database.errors import EncodeError
from tcms import protocol as proto
from tcms.parser import collect, count_frames
from tcms import faultlevel


def _encode(db, name, **signals):
    for sig in db.get_message_by_name(name).signals:
        signals.setdefault(sig.name, 0)
    return db.encode_message(name, signals)
"""


def _const_for(message: str) -> str:
    """报文名 -> proto 常量名（未知则原样字符串，编译期不炸）。"""
    return _MESSAGE_CONST.get(message, message)


def _compile_encode_bound(ex: object) -> Optional[str]:
    """encode_bound 类：expect 是 expect_encode_error / expect_encode_ok。"""
    setup = getattr(ex, "setup", [])
    expect = getattr(ex, "expect", [])
    if setup:
        return None  # encode_bound 不允许 setup
    if not expect:
        return None
    lines: list[str] = []
    for step in expect:
        args = step.args
        msg = args.get("message")
        sig = args.get("signal")
        val = args.get("value")
        if step.op == "expect_encode_error":
            lines.append(f'    with pytest.raises(EncodeError):\n        _encode(db, "{msg}", {sig}={val})')
        elif step.op == "expect_encode_ok":
            # 往返校验：编码成功 + 解码回原值（防「返回错误数据但长度不变」变异漏网）。
            # 枚举信号：decode 得 VAL_ 文本（如 'Info'），raw 值比较会假失败；
            # encode 输入必须是 raw int——若是文本（LLM 常见误解）编译期拒绝。
            texts = ENUM_SIGNAL_TEXTS.get((msg, sig))
            if isinstance(val, str):
                raise ValueError(
                    f"{msg}.{sig} 是枚举信号，encode 必须用 raw int 0-{max(texts) if texts else '?'}，"
                    f"不能用文本 {val!r}"
                )
            if texts and isinstance(val, int) and val in texts:
                decoded_expect = f'"{texts[val]}"'
            elif isinstance(val, int):
                decoded_expect = str(val)
            else:
                decoded_expect = repr(float(val))
            lines.append(
                f'    data = _encode(db, "{msg}", {sig}={val})\n'
                f"    assert len(data) == 8\n"
                f'    decoded = db.decode_message(db.get_message_by_name("{msg}").frame_id, data)\n'
                f'    assert decoded["{sig}"] == {decoded_expect}'
            )
        else:
            return None
    return "\n".join(lines)


def _compile_simulate(ex: object) -> Optional[str]:
    """simulate_inject 类：setup 注入 + expect 总线解码断言。"""
    setup = getattr(ex, "setup", [])
    expect = getattr(ex, "expect", [])
    if not setup or not expect:
        return None
    lines: list[str] = []
    msg_consts: list[str] = []
    for step in setup:
        args = step.args
        op = step.op
        if op == "set_speed":
            lines.append(f'    simulator.set_speed({args["kmh"]})')
        elif op == "set_handle":
            lines.append(f'    simulator.set_handle({args.get("position", 0)}, direction={args.get("direction", 1)})')
        elif op == "set_door_state":
            lines.append(f'    simulator.set_door_state({args["index"]}, {args["state"]})')
        elif op == "stop_message":
            const = _const_for(args["message"])
            msg_consts.append(const)
            lines.append(f"    simulator.stop_message(proto.{const})")
        elif op == "send_alarm":
            flags = {k: "True" if v else "False" for k, v in args.items() if k in ("Overspeed", "DoorNotClosed", "FireAlarm", "PantographDrop")}
            flag_str = ", ".join(f"{k}={v}" for k, v in flags.items())
            lines.append(f'    simulator.send_alarm({args.get("code", 1)}, {args.get("level", 2)}{", " + flag_str if flag_str else ""})')
        else:
            return None
    # 采集需要知道看哪些报文：从 expect 的 message 推断 + setup stop_message 的
    collect_ids = sorted(
        {_const_for(step.args["message"]) for step in expect if step.op in ("expect_signal", "expect_no_frames", "expect_frames_at_least") and "message" in step.args}
        | set(msg_consts)
    )
    if not collect_ids:
        return None
    collect_expr = ", ".join(f"proto.{c}" for c in collect_ids)
    # 注入后等待 + 采集
    wait = getattr(ex, "wait_ms", 150) / 1000.0
    collect = getattr(ex, "collect_ms", 300) / 1000.0
    lines.append(f"    time.sleep({wait})")
    lines.append(f"    frames = collect(bus, {collect}, {{{collect_expr}}}, db)")
    # 断言
    for step in expect:
        args = step.args
        if step.op == "expect_signal":
            const = _const_for(args["message"])
            sig = args["signal"]
            equals = args.get("equals")
            if isinstance(equals, str):
                cmp = f'== "{equals}"'
            else:
                cmp = f"== {equals}"
            lines.append(f'    assert frames[proto.{const}][-1]["{sig}"] {cmp}')
        elif step.op == "expect_no_frames":
            const = _const_for(args["message"])
            lines.append(f"    assert count_frames(bus, 0.5, proto.{const}) == 0")
        elif step.op == "expect_frames_at_least":
            const = _const_for(args["message"])
            lines.append(f"    assert count_frames(bus, 0.5, proto.{const}) >= {args.get('min_frames', 3)}")
        else:
            return None
    return "\n".join(lines)


def _compile_fault_scenario(ex: object) -> Optional[str]:
    """fault_scenario 类：注入故障 → 期望处置动作判等（faultlevel）。"""
    fault = getattr(ex, "fault", None)
    expect = getattr(ex, "expect", [])
    if not fault or not expect:
        return None
    lines: list[str] = []
    # 期望动作断言
    for step in expect:
        args = step.args
        if step.op == "expect_action":
            f = args.get("fault") or fault
            action = args.get("action")
            lines.append(f'    assert faultlevel.action_for("{f}") == "{action}"')
        else:
            return None
    return "\n".join(lines)


def compile_case(case: GeneratedCase) -> Optional[str]:
    """把一条生成用例编译为真实 pytest 函数源码；无 execution/不可编译返回 None。

    编译期语义错误（如枚举信号 encode 传文本）不崩溃——记不可编译返回 None，
    由 compile_rate 诚实反映（生成质量含"能不能编译"）。
    """
    if not case.name.startswith("test_"):
        return None
    ex = case.execution
    if ex is None:
        return None
    if not ex.is_executable():
        return None
    kind = ex.kind
    try:
        if kind == "encode_bound":
            body = _compile_encode_bound(ex)
            params = "db"
        elif kind == "simulate_inject":
            body = _compile_simulate(ex)
            params = "bus, db, simulator"
        elif kind == "fault_scenario":
            body = _compile_fault_scenario(ex)
            params = "db"
        else:
            return None
    except (ValueError, KeyError, TypeError):
        return None  # 语义错误 → 不可编译（诚实计 compile_rate 缺口）
    if body is None:
        return None
    return f"def {case.name}({params}):\n{body}\n"


@dataclass
class RealExecResult:
    """真实执行结果（口径对齐 docs/metrics.md exec_pass_rate）。"""

    total: int = 0
    compiled: int = 0
    passed: int = 0
    failed: int = 0
    stdout: str = ""
    report_path: Optional[str] = None

    @property
    def exec_pass_rate(self) -> float:
        return self.passed / self.compiled if self.compiled else 0.0

    @property
    def compile_rate(self) -> float:
        return self.compiled / self.total if self.total else 0.0

    def as_dict(self) -> dict[str, float | int | str | None]:
        return {
            "total": self.total,
            "compiled": self.compiled,
            "passed": self.passed,
            "failed": self.failed,
            "compile_rate": round(self.compile_rate, 3),
            "exec_pass_rate": round(self.exec_pass_rate, 3),
            "report_path": self.report_path,
        }


def build_test_file(cases: list[GeneratedCase]) -> tuple[str | None, int]:
    """把一批用例编译成 pytest 文件源码（纯函数，离线可测）。

    返回 (code, compiled_count)；无一条可编译时返回 (None, 0)。
    """
    bodies: list[str] = []
    compiled_count = 0
    for case in cases:
        body = compile_case(case)
        if body is None:
            continue
        bodies.append(body)
        compiled_count += 1
    if not bodies:
        return None, 0
    code = _HEADER + "\n\n" + "\n\n".join(bodies) + "\n"
    return code, compiled_count


def run_real(
    cases: list[GeneratedCase],
    upstream_root: str | Path,
    *,
    keep_artifacts: bool = False,
) -> RealExecResult:
    """把一批用例编译成单个 pytest 文件并在 tcms-can-test 仓库环境执行。

    约定：
    - 生成文件写入 ``<upstream>/tests/test_ai_generated_p2.py``（conftest 可见）；
      执行 ``<upstream .venv 或 PATH python> -m pytest <file> -q``，cwd=upstream_root
      让 conftest.py 与 tcms 包可导入；
    - keep_artifacts=True 时保留生成文件并回填 report_path（演示/审计用）。
    """
    root = Path(upstream_root)

    code, compiled_count = build_test_file(cases)
    if code is None:
        # 无一条可编译：不需要上游环境，直接返回（口径：compile_rate=0）
        return RealExecResult(total=len(cases), compiled=0, passed=0, failed=0)

    if not (root / "tests" / "conftest.py").is_file():  # pragma: no cover - 需上游
        raise FileNotFoundError(f"非 tcms-can-test 仓库根: {root}")
    tests_dir = root / "tests"

    # 写入上游 tests/（conftest 可见）——不落根目录避免污染
    gen_path = tests_dir / "test_ai_generated_p2.py"
    gen_path.write_text(code, encoding="utf-8")

    # 解释器：优先上游仓自带 venv（本地布局），否则用当前解释器
    # （CI/Linux 上游是干净 checkout，无 .venv；不依赖 PATH 上的 python）
    py = root / ".venv" / "Scripts" / "python.exe"
    if not py.is_file():  # 环境探测失败就退回当前解释器
        py = None
    cmd = [str(py) if py else sys.executable, "-m", "pytest", str(gen_path), "-q", "--no-header"]
    proc = subprocess.run(  # pragma: no cover - subprocess 需上游环境
        cmd,
        cwd=root,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=120,
    )
    stdout = proc.stdout
    passed = 0
    failed = 0
    # pytest -q 摘要：`N passed, M failed`（含 skipped 词需剥离）
    summary_line = [ln for ln in stdout.splitlines() if " passed" in ln or " failed" in ln]
    if summary_line:
        for ln in summary_line:
            m = re.search(r"(\d+) passed", ln)
            if m:
                passed = int(m.group(1))
            m = re.search(r"(\d+) failed", ln)
            if m:
                failed = int(m.group(1))
    report_path = str(gen_path) if keep_artifacts else None
    if not keep_artifacts:
        try:
            gen_path.unlink()
        except OSError:
            pass

    return RealExecResult(
        total=len(cases),
        compiled=compiled_count,
        passed=passed,
        failed=failed,
        stdout=stdout,
        report_path=report_path,
    )
